### PR TITLE
Feature/batch message relay

### PR DESCRIPTION
**Pull request by Tsuyoshi-Ishikawa**
# Action
- confirm 20 l2 transaction are bridge_transaction at once
- multicall to relay message

# Relevant pull request

Modified the code to check the operation of message-relayer's bridge
https://github.com/oasysgames/l1-l2-bridge-tutorial/pull/3
https://github.com/oasysgames/validator-publication/pull/22

Modify the code to use multicall at message-relayer and add how to check message-relayer's bridge performance
https://github.com/oasysgames/verse-layer-optimism/pull/12

# How to check bridge performance
I wrote document to check bridge performance.
https://github.com/oasysgames/verse-layer-optimism/pull/12/files

# Performance Result
I measured the processing time of 10 bridge tx (L2 to L1).

The procedure is as follows.
- Execute 100 bridge tx(L2→L1) with message-relayer stopped.
- Wait until the verification is completed.
- Restart message-relayer, and measure the time until the completion of message-relay.

## Before modification

```bash
time: 1300.538 sec
```
## After modification
```shell
time: 103.063 sec
```

# Optimize batch count
I set 20 transactions as the Optimal batch count.

The reason is the following.
- When I set 20 transactions as batch count, all multicall transaction is successful.
- When I set 50 or 100 transactions as batch count, It caused timeout of `eth_call` and unpredictable_gas_limit error.

### CODE REVIEW

**Comment by Tsuyoshi-Ishikawa** [comment]
# Modification
## Execute eth_estimateGas before executing multicall
https://github.com/oasysgames/oasys-optimism/pull/36/commits/ca434dd4db0cb05cffda7d05d74a06aef76b15f1

If error indicating that bridge is complete happened when executing estimateGas, We ignore the error.

## Performance Result
The procedure is as follows.

- Execute 100 bridge tx(L2→L1) with message-relayer stopped.
- Wait until the verification is completed.
- Restart message-relayer, and measure the time until the completion of message-relay.

```shell
# Normal
time: 1300.538 sec

# Max batch count is 5
time: 692.273 sec

# Max batch count is 10
time: 775.921 sec

# Max batch count is 20
time: 764.839 sec
```

Increasing the number of batches clogs the network and causes a timeout error, which takes longer to process.
```shell
2023-07-28 11:19:17 {"level":30,"time":1690510757487,"msg":"checking L2 block 82 ~ 101"}
2023-07-28 11:21:20 {"level":50,"time":1690510880906,"extra":{"message":"timeout (requestBody=\"{\\\"method\\\":\\\"eth_getLogs\\\",\\\"params\\\":[{\\\"fromBlock\\\":\\\"0x0\\\",\\\"toBlock\\\":\\\"latest\\\",\\\"address\\\":\\\"0xadfb0d1b239819cc45b7a863deeac9a54f97eb75\\\",\\\"topics\\\":[\\\"0x16be4c5129a4e03cf3350262e181dc02ddfb4a6008d925368c0899fcd97ca9c5\\\",\\\"0x0000000000000000000000000000000000000000000000000000000000000032\\\"]}],\\\"id\\\":8021,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", timeout=120000, url=\"http://host.docker.internal:8545/\", code=TIMEOUT, version=web/5.5.1)","stack":"Error: timeout (requestBody=\"{\\\"method\\\":\\\"eth_getLogs\\\",\\\"params\\\":[{\\\"fromBlock\\\":\\\"0x0\\\",\\\"toBlock\\\":\\\"latest\\\",\\\"address\\\":\\\"0xadfb0d1b239819cc45b7a863deeac9a54f97eb75\\\",\\\"topics\\\":[\\\"0x16be4c5129a4e03cf3350262e181dc02ddfb4a6008d925368c0899fcd97ca9c5\\\",\\\"0x0000000000000000000000000000000000000000000000000000000000000032\\\"]}],\\\"id\\\":8021,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", timeout=120000, url=\"http://host.docker.internal:8545/\", code=TIMEOUT, version=web/5.5.1)\n    at Logger.makeError (/opt/optimism/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)\n    at Timeout._onTimeout (/opt/optimism/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/src.ts/index.ts:207:35)\n    at listOnTimeout (node:internal/timers:557:17)\n    at processTimers (node:internal/timers:500:7)","code":"TIMEOUT"},"msg":"caught an unhandled exception"}
```

## Optimize batch count
Following the above result, I set 5 to batch max count.
https://github.com/oasysgames/oasys-optimism/pull/36/commits/ab4e7ef1a7b4b5a07dc3434e59e48c41e5e64c84

**Comment by Tsuyoshi-Ishikawa** [comment]
# Modification 2

## Set gasLimit before executing Multicall
https://github.com/oasysgames/oasys-optimism/pull/36/commits/3f1665a44900cc0ec167895bb9f35f09343cd6e4

## Set max_batch_size from options
https://github.com/oasysgames/oasys-optimism/pull/36/commits/52e14a7c7c19bc99504f50ecce7c5f5a5d9199b3

## Enable that verified message is always relayed to L1
https://github.com/oasysgames/oasys-optimism/pull/36/commits/6d3c664fe9f787b4e5b6fcafe370eec0f734cf30

### Confirmation
As the following log, I am checking `103~123` blocks, but only verifid `103~112` blocks of them are performing multicall.
Previously, multicall was not performed until all 103 ~ 123 block messages were verified.

```shell
2023-08-14 10:15:06 {"level":30,"time":1691975706370,"msg":"checking L2 block 103 ~ 123"}
2023-08-14 10:15:11 {"level":30,"time":1691975711183,"msg":"txs are finalized, relaying: 103 ~ 112"}
2023-08-14 10:15:21 {"level":30,"time":1691975721869,"msg":"relayer sent multicall: 0x35738422712a92db7a8002f76835ad1cb36f7783fffde96f69f3e4cf54a5bb90"}
```

## Performance Result
The procedure is as follows.

- Execute 100 bridge tx(L2→L1) with message-relayer stopped.
- Wait until the verification is completed.
- Restart message-relayer, and measure the time until the completion of message-relay.

```shell
# Normal
time: 1300.538 sec

# Max batch count is 5
time: 578.319 sec

# Max batch count is 10
time: 428.261 sec

# Max batch count is 20
time: 386.242 sec

# Max batch count is 50
time: 1829.188 sec
```

I set 20 as  optimal max message batch size.
https://github.com/oasysgames/oasys-optimism/pull/36/commits/c31df835232bfa32ee6abb679b341f7cabe5dca8

**Comment by Tsuyoshi-Ishikawa** [comment]
# Modification 3

## Set Multicall gas limit not setting max message batch size
Default multicall gas limit is 1500000.
https://github.com/oasysgames/oasys-optimism/pull/36/commits/7870b560e4f9b03d12b4a371076542d210baec19

## Performance Result
The procedure is as follows.

- Execute 100 bridge tx(L2→L1) with message-relayer stopped.
- Wait until the verification is completed.
- Restart message-relayer, and measure the time until the completion of message-relay.

```shell
# Single message relay
time: 1300.538 sec

# Multi message relay and Multicall gas limit is 1500000
time: 732.375 sec
```

**Comment by Tsuyoshi-Ishikawa** [comment]
# Modification 4
## Set newMulticallEstimateGas
https://github.com/oasysgames/oasys-optimism/pull/36/commits/7a10c16513ae135859323805dacbe5dec7a7d8b1

## Performance Result
The procedure is as follows.

- Execute 100 bridge tx(L2→L1) with message-relayer stopped.
- Wait until the verification is completed.
- Restart message-relayer, and measure the time until the completion of message-relay.

```shell
# Single message relay
time: 1300.538 sec

# Multi message relay and Multicall gas limit is 1500000
time: 726.509 sec
```

**Review by ironbeer — APPROVED** [review]
👍

**Pull request merged**
